language: r
r_packages:
  - git2r
  - archivist
  - jsonlite
  - httr
  - digest
  - knitr
  - rmarkdown
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

sudo: required
